title: Jamal M
logo: https://github.com/Jamal876/jamal876.github.io/blob/main/DP%202.jpg
description: jamaltajtheen@gmail.com  <br>  +91-7448560876 <br> www.linkedin.com/in/Jamal M
show_downloads: false
theme: jekyll-theme-minimal
